image: docker:stable

services:
  - docker:dind

before_script:
  - docker info

build:
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  stage: build
