image: docker:stable

stages:
  - build

variables:
  DOCKER_REGISTRY: 972400558605.dkr.ecr.us-east-1.amazonaws.com/sampledatetime
  AWS_DEFAULT_REGION: us-east-1
  APP_NAME: sampledatetime
  CI_VERSION: "1.0.${CI_JOB_ID}"


build:
  stage: build
  services:
    - docker:dind
  
  before_script:
#    - apk add --no-cache curl jq python3 py3-pip
#    - pip install awscli
#    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
#    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
#    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 972400558605.dkr.ecr.us-east-1.amazonaws.com
#    - aws --version
    - docker info
    - docker --version
    - echo $CI_VERSION


  script:
    - docker build -t sampledatetime-v$CI_VERSION -f Dockerfile .
    - docker images
#    - docker tag sampledatetime:latest 972400558605.dkr.ecr.us-east-1.amazonaws.com/sampledatetime:latest
#    - docker push 972400558605.dkr.ecr.us-east-1.amazonaws.com/sampledatetime:latest

  after_script:
    - apk update && apk add git
    - git --version
    - git remote remove origin
    - git remote add origin https://oauth2:$gitlab_access_token@gitlab.com/Administrator/sampledatetime
    - git config user.email sarfarazusaf019@gmail.com
    - git config user.name root
    - git tag -a v0.0 -m "Release version 0.0"
    - git tag

