image: docker:stable

stages:
  - build

build:
  stage: build
  script:
    - systemctl start docker
    - docker build -t sampledatetime-image -f Dockerfile .
    - echo 'image build'
    - docker images

