image: docker:stable

stages:
  - build

variables:
  DOCKER_REGISTRY: 972400558605.dkr.ecr.us-east-1.amazonaws.com/sampledatetime
  AWS_DEFAULT_REGION: us-east-1
  APP_NAME: sampledatetime


build:
  stage: build
  services:
    - docker:dind
  
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - sudo ./aws/install
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 972400558605.dkr.ecr.us-east-1.amazonaws.com
    - aws --version
    - docker info
    - docker --version
  script:
    - docker build -t sampledatetime -f Dockerfile .
    - echo 'image build'
    - docker images
    - docker tag sampledatetime:latest 972400558605.dkr.ecr.us-east-1.amazonaws.com/sampledatetime:latest
    - docker push 972400558605.dkr.ecr.us-east-1.amazonaws.com/sampledatetime:latest

