image: docker:stable

stages:
  - build

variables:
  DOCKER_REGISTRY: 972400558605.dkr.ecr.us-east-1.amazonaws.com/sampledatetime
  AWS_DEFAULT_REGION: us-east-1
  APP_NAME: sampledatetime
  DOCKER_HOST: tcp://0.0.0.0:2375

build:
  stage: build
  script:
    - docker build -t sampledatetime-image -f Dockerfile .
    - echo 'image build'
    - docker images
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 972400558605.dkr.ecr.us-east-1.amazonaws.com
    - docker tag sampledatetime:latest 972400558605.dkr.ecr.us-east-1.amazonaws.com/sampledatetime:latest
    - docker push 972400558605.dkr.ecr.us-east-1.amazonaws.com/sampledatetime:latest

