stages:
  - build
  - buildimage
before_script:
  - 'dotnet restore'

build:
  stage: build
  image: docker:latest
  script:
    - dotnet build
    - dotnet publish --output ./publish
    - pwd
    - echo 'build completed'

buildimage:
  stage: buildimage
  script:
    - docker build -t sampledatetime
    - docker run -d --name sampledatetimecontainer -p 5000:8080 sampledatetime


