image: docker:stable

stages:
  - nuget restore
  - build
  - publish

variables:
  DOCKER_REGISTRY: 972400558605.dkr.ecr.us-east-1.amazonaws.com/sampledatetime
  AWS_DEFAULT_REGION: us-east-1
  APP_NAME: sampledatetime
  CI_VERSION: "1.0.${CI_JOB_ID}"
  IMAGE_NAME: sampledatetime-v$CI_JOB_ID

#workflow:
#  rules:
#    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  
nuget restore:
  image: mcr.microsoft.com/dotnet/sdk:6.0.405
  stage: nuget restore
  script:
    - dotnet restore

build:
  image: mcr.microsoft.com/dotnet/sdk:6.0.405
  stage: build
  script:
    - dotnet build

publish:
  stage: publish
  services:
    - docker:dind
  #before_script:
  #  - apk add --no-cache curl jq python3 py3-pip
  #  - pip install awscli
  #  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  #  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  #  - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 972400558605.dkr.ecr.us-east-1.amazonaws.com
  #  - aws --version
  #  - docker info
  #  - docker --version
  script:
    - dotnet publish --output ./publish
    #- docker build -t $IMAGE_NAME:$CI_VERSION -f Dockerfile .
    #- docker images
    - pwd
#    - docker tag sampledatetime:$IMAGE_NAME 972400558605.dkr.ecr.us-east-1.amazonaws.com/sampledatetime:$IMAGE_NAME
#    - docker push 972400558605.dkr.ecr.us-east-1.amazonaws.com/sampledatetime:$IMAGE_NAME
#    - echo $CI_PROJECT_PATH
#    - echo $CI_PROJECT_URL
#    - echo $CI_PROJECT_DIR
  artifacts:
    expire_in: 1 hour
    paths:
      - /builds/gitlab-instance-a6e4347b/sampledatetime

#  after_script:
#    - apk update && apk add git
#    - git --version
#    - git remote remove origin
#    - git remote add origin http://oauth2:$gitlab_access_token@ec2-3-214-28-52.compute-1.amazonaws.com/gitlab-instance-a6e4347b/sampledatetime
#    - git config user.email $git_email
#    - git config user.name $git_user
#    - git tag -a v0.$CI_VERSION -m "Release version 0.$CI_VERSION"
#    - git push --tags
#    - git push origin v0.$CI_VERSION
#    - git tag
#  only:
#    - master