before_script:
  - 'dotnet restore'

build:
  stage: build
  script:
    - 'dotnet build --no-restore'

deploy:
  stage: deploy
  script:
      - docker build -t sampledatetime
      - docker run -d --name sampledatetimecontainer -p 5000:8080 sampledatetime
